#!/bin/bash                                                                     

# $1 == 1 - for change
if [[ $1 = "1" ]]
  then
    for file in *.html
      do
        if [[ ! -f "$file" ]]
        then
          continue
        fi
        # The file has already been changed.
        if grep --quiet '\<title\>.*КИТ.*' $file
        then
          sed -i.backup -e '/<title>.*/s/КИТ/ШРИ/g' $file
        fi                                                  
      done
# $1 == 0 - for rollback
else if [[ $1 = "0" ]]
  then
    for file in *.html.backup
      do
        if [[ ! -f "$file" ]]
        then
            continue
        fi
          cp $file ${file%.*}
          rm $file                                              
      done
     else
       echo "Wrong arguments! Try 0 or 1."
     fi
fi
